# Generated by Django 2.1.7 on 2019-03-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='codebase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='代码名称')),
                ('ps', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('file', models.FileField(upload_to='codebase/%Y%m%d78603', verbose_name='代码文件')),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('utime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '代码',
                'verbose_name_plural': '资产管理',
                'db_table': 'codebase',
            },
        ),
    ]
